/**
 * API Route: /api/single-research/[id]
 * 
 * GET    - Get single research entry by ID
 * PATCH  - Update research entry
 * DELETE - Delete research entry
 */

import { NextRequest, NextResponse } from 'next/server';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import type { SingleVehicleResearchUpdate } from '@/lib/supabase/types';

interface RouteParams {
  params: Promise<{ id: string }>;
}

// GET /api/single-research/[id] - Get single entry
export async function GET(
  request: NextRequest,
  { params }: RouteParams
) {
  try {
    const { id } = await params;
    const supabase = createServerSupabaseClient();
    
    // Validate UUID format
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    if (!uuidRegex.test(id)) {
      return NextResponse.json(
        { error: 'Invalid research ID format' },
        { status: 400 }
      );
    }
    
    const { data, error } = await supabase
      .from('single_vehicle_research')
      .select('*')
      .eq('id', id)
      .single();
    
    if (error) {
      if (error.code === 'PGRST116') {
        return NextResponse.json(
          { error: 'Single vehicle research not found' },
          { status: 404 }
        );
      }
      console.error('Error fetching single vehicle research:', error);
      return NextResponse.json(
        { error: 'Failed to fetch single vehicle research', details: error.message },
        { status: 500 }
      );
    }
    
    return NextResponse.json(data);
  } catch (error) {
    console.error('Unexpected error in GET /api/single-research/[id]:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

// PATCH /api/single-research/[id] - Update entry
export async function PATCH(
  request: NextRequest,
  { params }: RouteParams
) {
  try {
    const { id } = await params;
    const supabase = createServerSupabaseClient();
    const body: SingleVehicleResearchUpdate = await request.json();
    
    // Validate UUID format
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    if (!uuidRegex.test(id)) {
      return NextResponse.json(
        { error: 'Invalid research ID format' },
        { status: 400 }
      );
    }
    
    // Prepare update data
    const updateData: any = { ...body };
    
    // Automatically update status based on state
    if (updateData.completed_steps) {
      if (updateData.completed_steps.includes(5)) {
        updateData.status = 'completed';
      } else if (updateData.completed_steps.includes(4)) {
        updateData.status = 'generating';
      } else if (updateData.completed_steps.includes(3)) {
        updateData.status = 'corpus_ready';
      } else if (updateData.completed_steps.includes(2)) {
        updateData.status = 'scraping';
      } else if (updateData.completed_steps.length > 0) {
        updateData.status = 'draft';
      }
    }
    
    // Remove display_name if present (auto-generated by database)
    delete updateData.display_name;
    
    const { data, error } = await (supabase as any)
      .from('single_vehicle_research')
      .update(updateData)
      .eq('id', id)
      .select('id, display_name, current_step, completed_steps, status, updated_at')
      .single();
    
    if (error) {
      if (error.code === 'PGRST116') {
        return NextResponse.json(
          { error: 'Single vehicle research not found' },
          { status: 404 }
        );
      }
      console.error('Error updating single vehicle research:', error);
      return NextResponse.json(
        { error: 'Failed to update single vehicle research', details: error.message },
        { status: 500 }
      );
    }
    
    return NextResponse.json({
      ...data,
      message: 'Single vehicle research updated successfully',
    });
  } catch (error) {
    console.error('Unexpected error in PATCH /api/single-research/[id]:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

// DELETE /api/single-research/[id] - Delete entry
export async function DELETE(
  request: NextRequest,
  { params }: RouteParams
) {
  try {
    const { id } = await params;
    const supabase = createServerSupabaseClient();
    
    // Validate UUID format
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    if (!uuidRegex.test(id)) {
      return NextResponse.json(
        { error: 'Invalid research ID format' },
        { status: 400 }
      );
    }
    
    const { error } = await supabase
      .from('single_vehicle_research')
      .delete()
      .eq('id', id);
    
    if (error) {
      if (error.code === 'PGRST116') {
        return NextResponse.json(
          { error: 'Single vehicle research not found' },
          { status: 404 }
        );
      }
      console.error('Error deleting single vehicle research:', error);
      return NextResponse.json(
        { error: 'Failed to delete single vehicle research', details: error.message },
        { status: 500 }
      );
    }
    
    return NextResponse.json({
      message: 'Single vehicle research deleted successfully',
    });
  } catch (error) {
    console.error('Unexpected error in DELETE /api/single-research/[id]:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
